#this code passes the Rinex 3 filename generated by BNC's NtripClient to gnssrefl's rinex2snr module
import argparse
import os

parser=argparse.ArgumentParser()
parser.add_argument("-Rinex3FileName", help="Rinex3 filename", type=str)
args = parser.parse_args()
Rinex3FileName = args.Rinex3FileName
filename = Rinex3FileName[-38:]
os.system('rinex2snr ' + filename)
