#this code passes the Rinex 3 filename generated by BNC's NtripClient to gnssrefl's rinex2snr module
import argparse
import os

parser=argparse.ArgumentParser()
parser.add_argument("-Rinex3FileName", help="Rinex3 filename", type=str)
args = parser.parse_args()
Rinex3FileName = args.Rinex3FileName
filename = Rinex3FileName[-38:]
site_id = filename[0:9]
year = filename[12:16]
doy = filename[17:19]
hrmn = filename[19:23]
fileperiod = filename[24:27]
stream = filename[10:11]
samplerate = int(str(filename[28:30]))
os.system('rinex2snr ' + site_id + ' ' + year + ' ' + doy + ' -nolook True -overwrite True -orb ultra -stream ' + stream + ' -samplerate ' + str(samplerate) + ' -overwrite True -mk True -hrmn ' + hrmn + ' -fileperiod ' + fileperiod)
